language: node_js
node_js:
  - 10

os:
  - linux
  - osx

cache:
  directories:
    - node_modules

script:
  - node --version
  - npm --version
  - npm ls grpc wechaty wechaty-puppet wechaty-puppet-mock wechaty-puppet-puppeteer wechaty-puppet-padplus
  - echo "Testing Started ..."
  - npm test
  - echo "Testing Finished."

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/41a19fbf1d54a04e5217
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
  email:
    on_success: change
    on_failure: change
